### ISSUE TITLE
Switch Github mirror

### ISSUE THREAD

**Issue by okuoku** [scheme-containers/s7#1]
It seems the only recommended mirror is https://github.com/wdouglass/s7 

- Mentioned since Jan2020: https://github.com/wdouglass/s7/commit/be4aa6628f9f032e074f7f9bb522263a3dec8a93#diff-31e2e7bdfb44d6627cda40c0fffcc30bR155
- The author asked not to use other mirrors in Mar2020: https://github.com/wdouglass/s7/commit/30e1853b3a91d2bff8adfff0bd6027e28c7aff28#diff-31e2e7bdfb44d6627cda40c0fffcc30bR158

**Comment by lassik** [comment]
I checked that recommended mirror earlier but it wasn't up to date. That seems to be fixed: the last commit is from yesterday. Feel free to push a change to this repo.

**Comment by lassik** [comment]
We should start a `scheme-mirrors` organization and consolidate all the mirrors in there.

**Comment by okuoku** [comment]
(Edited post; link was wrong for Mar2020 ...)

Is there any reason not to use the original Subversion? If it's okay, I'll try to switch to the official repository (Subversion).

Regarding current `spurious` mirror, actually I pay VPS and traffic for it(operated by the other guys). So in case there is concern on its availability, keeping it as-is can be a choice as I know who runs the mirror. 

Anyway, mirroring repository has complex pros/cons, sometimes not technical; Ruby recently moved to Git, but not GitHub mostly because of a guy (who invented `git-svn`) does not like it. I believe we need to be respectful to the authors; it'd be better trying hard to use the original as-is. Some folks intentionally choose non-Git VCS by their own reasons/purposes. 

In practice, as GitHub cannot disable pull request, mirror repository receives pull requests even it clearly have "mirror" on its name https://github.com/SDL-mirror/SDL/pulls?q=is%3Apr+is%3Aclosed https://github.com/spurious/SDL-mirror/pulls?q=is%3Apr+is%3Aclosed .

OTOH, Yunibase tries to git-submodule-fy every supported implementations. This is not only for reproducibility but also for developing upstream patches.. Git is really good for it -- embedding source history into other project. To avoid any confusions, I have intentionally avoided "scheme" name on the projects(yuni/yunibase) to emphasize it is for a particular product(yuni) and not for the Scheme standard.

**Comment by lassik** [comment]
> Is there any reason not to use the original Subversion? If it's okay, I'll try to switch to the official repository (Subversion).

Very good point. There is no particular reason to prefer the git mirror; I just used it out of habit. Subversion is not familiar to me.

> I believe we need to be respectful to the authors

I agree. I would coordinate with the author of each implementation before mirroring it under a `scheme-mirrors` organization. An unofficial mirror is less useful and trustworthy for all.

> In practice, as GitHub cannot disable pull request, mirror repository receives pull requests even it clearly have "mirror" on its name

I didn't know it cannot be disabled. Hence in practice we would have to manually close any PRs.

> I have intentionally avoided "scheme" name on the projects(yuni/yunibase) to emphasize it is for a particular product(yuni) and not for the Scheme standard.

This is good since you aim to develop a particular flavor of Scheme. scheme-containers is intended to have a feedback loop with the authors of each Scheme implementations so that we work together with them whenever we can reach them.

**Comment by lassik** [comment]
If you know how to use subversion, feel free to change s7 from Git to svn :)

**Comment by lassik** [comment]
> Regarding current `spurious` mirror, actually I pay VPS and traffic for it(operated by the other guys). So in case there is concern on its availability, keeping it as-is can be a choice as I know who runs the mirror.

Great. This could be very useful for coordinating all the backend stuff on one server if a `scheme-mirrors` project ever takes off. But of course, please refuse if you feel it would be too much sysadmin burden for you :) I don't really have enough energy right now to email all the people required to put `scheme-mirrors` together. And it doesn't need to be my initiative - someone else can do it just as well.

**Comment by lassik** [comment]
cc @weinholt - you may have a general interest in the stuff discussed in this thread

**Comment by okuoku** [comment]
Okay, give me some time (to migrate to Svn).

**Comment by lassik** [comment]
s7 now has an official git repo at https://cm-gitlab.stanford.edu/bil/s7. I updated our container to use it.
